# Generated by Django 3.2.23 on 2024-01-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=100)),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.department')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_assigned_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subjects')),
                ('TEACHERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('register_no', models.CharField(max_length=100)),
                ('identification_mark', models.CharField(max_length=1000)),
                ('joined_clubs', models.CharField(max_length=1000)),
                ('blood_group', models.CharField(max_length=100)),
                ('licence_no', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(max_length=2000)),
                ('about', models.CharField(max_length=1000)),
                ('reg_no', models.CharField(max_length=100)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.batches')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=200)),
                ('STUDENTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.students')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_type_materials', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.course')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=200)),
                ('STUDENTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.students')),
                ('SUBJECT_ASSIGNED_TEACHERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subject_assigned_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.department')),
                ('TEACHERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=2000)),
                ('date', models.CharField(max_length=100)),
                ('STUDENTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.students')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='DEPARTMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.department'),
        ),
        migrations.AddField(
            model_name='batches',
            name='DEPARTMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.department'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('STUDENTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.students')),
                ('SUBJECT_ASSIGNED_TEACHERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subject_assigned_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Allocateclasstutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.batches')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.course')),
                ('TEACHERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.teachers')),
            ],
        ),
    ]
