# Generated by Django 3.2.23 on 2024-01-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.login'),
        ),
    ]
