# Generated by Django 3.2.23 on 2024-01-04 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0002_students_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='SUBJECT_ASSIGNED_TEACHERS',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='SUBJECT_ASSIGNED_TEACHERS',
        ),
        migrations.RemoveField(
            model_name='students',
            name='register_no',
        ),
        migrations.AddField(
            model_name='marks',
            name='SUBJECTS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='internal_marks',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
