# Generated by Django 3.2.23 on 2024-01-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0003_auto_20240104_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='SUBJECTS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subjects'),
            preserve_default=False,
        ),
    ]
