# Generated by Django 3.2.23 on 2024-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0004_materials_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
    ]
