# Generated by Django 3.2.23 on 2024-02-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0006_auto_20240109_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_assigned_teachers',
            name='BATCH',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.batches'),
            preserve_default=False,
        ),
    ]
