# Generated by Django 3.2.23 on 2024-02-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0007_subject_assigned_teachers_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_assigned_teachers',
            name='COURSE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.course'),
            preserve_default=False,
        ),
    ]
