# Generated by Django 3.2.23 on 2024-02-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0008_subject_assigned_teachers_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='SUBJECT_ASSIGNED_TEACHERS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DeptautoApp.subject_assigned_teachers'),
            preserve_default=False,
        ),
    ]
