# Generated by Django 3.2.23 on 2024-02-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0009_attendence_subject_assigned_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='marks',
            new_name='sem',
        ),
    ]
