# Generated by Django 3.2.23 on 2024-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0011_remove_attendence_subject_assigned_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='sem',
            field=models.CharField(default='sem1', max_length=30),
            preserve_default=False,
        ),
    ]
