# Generated by Django 3.2.23 on 2024-03-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0012_attendence_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
