# Generated by Django 3.2.23 on 2024-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeptautoApp', '0013_delete_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='phone_no',
            field=models.CharField(max_length=30),
        ),
    ]
